version: '3.9'
services:
  app:
    build:
      context: ./images/api
    container_name: wallet_api
    environment:
      - PORT=8080
      - DBHOST=wallet_db
      - DBUSER=digitalwallet
      - DBPASS=digitalwallet
      - DBNAME=digitalwallet
    networks:
      - api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: wallet_db
    environment:
      - POSTGRES_USER=digitalwallet
      - POSTGRES_PASSWORD=digitalwallet
      - DB_DATABASE=digitalwallet
      - POSTGRES_ROOT_PASSWORD=digitalwallet
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - api
    ports:
      - 5432:5432
volumes:
  db:
networks:
  api:
    driver: "bridge"